package com.siby.generators;

import java.util.Random;

/**
 * Provides template for random value generation
 * for a given type T
 *
 * @param <T> random value of T will be generated by the implementing class
 */
public interface Generator<T> {
    Random RANDOM = new Random();

    T next();
}
